### ISSUE TITLE
请教作者,项目运行报错如何解决

### ISSUE THREAD

**Issue by QQiTong** [pure-admin/pure-admin-micro#3]
执行完pnpm install 后,再执行  pnpm micro-app:dev 后 ,控制台报如下错误,请问作者,应该如何解决?

![image](https://github.com/pure-admin/pure-admin-micro/assets/10771777/e9d5082d-c03b-4fae-a0bb-e58276ec8856)

**Comment by Ten-K** [comment]
> 执行完pnpm install 后,再执行 pnpm micro-app:dev 后 ,控制台报如下错误,请问作者,应该如何解决?
> 
> ![image](https://user-images.githubusercontent.com/10771777/255813003-e9d5082d-c03b-4fae-a0bb-e58276ec8856.png)

pnpm需要使用v7版本
